title: Between a rock and a hard Space
name: patricab
user_description: The blog of a mildly irritated Electrical Engineering student
tagline: The blog of a mildly irritated Electrical Engineering student
profile_pic: /assets/img/microchip_black.png
avatar: /assets/img/microchip_black.png
favicon: /assets/img/microchip_black.png
copyright_name: Patric A. Berthelsen
baseurl: "" # the subpath of your site, e.g. /blog
url: "patricab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

social:
  name: Patric A.B
  links:
    - https://www.linkedin.com/in/patric-andre-berthelsen/
    - https://github.com/patricab

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-seo-tag

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
